name: benchmark_gnn
channels:
- pytorch 
- dglteam
- conda-forge
- anaconda
- defaults
dependencies:
- python=3.11
- python-dateutil
- pip
- pytorch
- torchvision
- pillow
- numpy
- matplotlib
- tensorboard
- tensorboardx
- future
- absl-py
- networkx
- scikit-learn
- scipy
- notebook
- h5py
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jupyter=
- jupyter_client
- jupyter_console
- jupyter_core
- plotly
- scikit-image
- requests
- tqdm
- pip:
  - tensorflow
  - tensorflow-estimator
  - tensorboard
  - ogb